---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: bonjourinc
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
    - hostname: paulynomial.com
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: "*.paulynomial.com"
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: paulinomial.com
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: "*.paulinomial.com"
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: paul-kiernan.com
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: "*.paul-kiernan.com"
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: bonjourinc.com
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: valheim.paulynomial.com
      service: tcp://valheim-service.valheim.svc.cluster.local:2456
    - hostname: "*.bonjourinc.com"
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - service: http_status:404
