---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: bonjourinc
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
    - hostname: bonjourinc.com
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - hostname: "*.bonjourinc.com"
      service: http://ingress-nginx-controller.networking.svc.cluster.local:80
    - service: http_status:404
