---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: bonjourinc
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: bonjourinc.com
      service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    - hostname: *.bonjourinc.com
      service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    - service: http_status:404
