---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 1m
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/server-snippet: |
                proxy_ssl_verify off;
        host:
          name: "rook-ceph.${SECRET_DOMAIN}"
          path: "/"
