apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taqueria-bonjour
  labels:
    app: taqueria-bonjour
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: taqueria-bonjour
  template:
    metadata:
      labels:
        app: taqueria-bonjour
    spec:
      containers:
      - name: frontend
        image: ghcr.io/paulkiernan/taqueria-bonjour-frontend:1.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_BACKEND_API_URL
          value: "https://bonjour.paulynomial.com/api"
        - name: REACT_APP_GOOGLE_ANALYTICS_ENABLE_DEBUG
          value: "false"
        ports:
        - containerPort: 80
