---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-rook-ceph-fs
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
