---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        path: /
        hosts:
          - "grafana.${SECRET_DOMAIN}"
      plugins: "grafana-piechart-panel"
      adminPassword: "${GRAFANA_DASHBOARD_PASSWORD}"
    prometheus:
      prometheusSpec:
        serviceMonitorNamespaceSelector: {}  # auto discover all service monitors accross all namespaces
        serviceMonitorSelector: {}  # auto discover all service monitors accross all namespaces
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: prometheus
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: ceph-filesystem
              resources:
                requests:
                  storage: 10Gi
    nodeExporter:
      jobLabel: node-exporter
    prometheus-node-exporter:
      podLabels:
        jobLabel: node-exporter
