---
  # Disable those noisy LEDs
- include: leds/act.yml
  when: act_led_disabled

- include: leds/pwr.yml
  when: pwr_led_disabled

# Install base packages
- include: packages/htop.yml

- name: Enable cgroup_memory, cgroup_enable # needed for kubeadm
  become: yes
  become_user: root
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '(?=.*root)(?!.*cgroup_memory=1 cgroup_enable=memory cgroup_enable=cpuset)(.+)'
    backrefs: yes
    line: '\1 cgroup_memory=1 cgroup_enable=memory cgroup_enable=cpuset'

# Installs systemd service for enabling promisc on wlan0
#   This is necessary for wlan0 to respond to ARP pings:
#   https://github.com/raspberrypi/linux/issues/2677
- name: install promiscuous-mode@.service
  become: yes
  become_user: root
  template:
    src: promiscuous-mode@.service
    dest: /etc/systemd/system/promiscuous-mode@.service

- name: start promiscuous-mode@wlan0.service
  become: yes
  become_user: root
  systemd:
    state: stopped
    enabled: false
    name: promiscuous-mode@wlan0.service

# Disable WiFi now that we're on a wired network
- name: mask wpa_supplicant.service
  become: yes
  become_user: root
  systemd:
    masked: yes
    name: wpa_supplicant.service

- name: stop netplan-wpa-wlan0.service
  become: yes
  become_user: root
  systemd:
    masked: yes
    name: netplan-wpa-wlan0.service
