---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
  values:
    replicaCount: 4
    maxSurge: 1
    maxUnavailable: 1
    serviceWeb:
      loadBalancerIP: 192.168.7.254
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.7.254
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    antiaff:
      enabled: true
      avoidRelease: pihole
      strict: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - "pihole.${SECRET_DOMAIN}"
    dnsmasq:
      customDnsEntries:
        - "address=/pihole.${SECRET_DOMAIN}/${INGRESS_NGINX_LB}"
        - "address=/rook-ceph.${SECRET_DOMAIN}/${INGRESS_NGINX_LB}"
        - "address=/grafana.${SECRET_DOMAIN}/${INGRESS_NGINX_LB}"
        - "address=/bonjour.${SECRET_DOMAIN}/${INGRESS_NGINX_LB}"
    whitelist:
      - "${SECRET_DOMAIN}"
      - "pihole.${SECRET_DOMAIN}"
      - "rook-ceph.${SECRET_DOMAIN}"
      - "grafana.${SECRET_DOMAIN}"
      - "bonjour.${SECRET_DOMAIN}"
    podAnnotations:
      prometheus.io/port: '9617'
      prometheus.io/scrape: 'true'
    monitoring:
      sidecar:
        enabled: true
        port: 9617
    adminPassword: "${PIHOLE_DASHBOARD_PASSWORD}"
