---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: pihole-kubernetes
        namespace: pihole
  values:
    configInline:
      serviceWeb:
        loadBalancerIP: 192.168.7.254
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc
        type: LoadBalancer

      serviceDns:
        loadBalancerIP: 192.168.7.254
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc
        type: LoadBalancer
