apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
    #- podmonitor.yaml
configMapGenerator:
  - name: pihole-grafana-dashboards
    files:
      - pi-hole-exporter.json
    options:
      labels:
        grafana_dashboard: pihole
