apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - podmonitor.yaml
configMapGenerator:
  - name: pihole-grafana-dashboards
    namespace: monitoring
    files:
      - grafana-dashboard.json
    options:
      labels:
        grafana_dashboard: pihole
