---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pihole
  namespace: pihole
  labels:
    app.kubernetes.io/part-of: pihole
spec:
  namespaceSelector:
    matchNames:
      - pihole
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pihole
  podMetricsEndpoints:
    - port: "9617"
