---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pihole
  namespace: pihole
  labels:
    app.kubernetes.io/part-of: prometheus
spec:
  namespaceSelector:
    matchNames:
      - pihole
  selector:
    matchLabels:
      app: pihole
  podMetricsEndpoints:
    - port: "9617"
