---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pihole-prometheus-exporter
  namespace: pihole
  labels:
    app.kubernetes.io/part-of: prometheus
spec:
  namespaceSelector:
    matchNames:
      - pihole
  selector:
    matchLabels:
      app: pihole
  podMetricsEndpoints:
    - path: /metrics
      port: prometheus
