apiVersion: v1
kind: Secret
metadata:
    name: valheim-secrets
    namespace: valheim
type: Opaque
data:
    password: ENC[AES256_GCM,data:TkrjL/V8M2wM7NVRlyPGTw==,iv:Vg2eN6O6nr6ulVtFmNHOwqoO/ZwzF460JKheXUQhX8I=,tag:YE+L5exUW8BZv44uS6DNSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-11T01:51:04Z"
    mac: ENC[AES256_GCM,data:XwxW6DrVv4xBzuSh2sw1cKG22sw2PL4R9wKyTkCv+JK0nckbGkvUPWcL6JMVs//OqpJPUNW3ORUimcO7b+pOgyduIprJGbsIig/Av6oVNct6WNaouxuobK/Oo31z3U4gA5LIOsp2zH0uZLU28XekcHhwAqIaiCsBolrr6qCXxUY=,iv:fhs+AP17xibwjc/EUEOA/+6xIdb/OS8Bkt0+JmHXU6A=,tag:WOcxX/SEqQDyH0P5MjDWtg==,type:str]
    pgp:
        - created_at: "2021-09-11T01:51:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwgdmCUx4uNqAQ/+MNg975E0NWKINkoXip9Q5VzUW4uouP2s+aJIkO1pJrNU
            I3x7rQxPQYnzTXL0oH4en5NCk3OK/70BwCxBO7v8/KezcAr0ybI6QEm2FULI+DuL
            cWzOBAFZoAqEx0X8IX/DQMJRCSJOtXCkkH5Hu4xaf4KZSqL+EpAW6xe80i82UNtN
            Jo30mVsLrSrcp+gR6ONWl5cPwYFl5XiU8fOv1O60fJXzYKViTQR1bV8dIWNlNpk8
            Qt4k8ac3ZvErWnQf0Cc3GmkLSCXgPyEGTrFb5J4rsDHKZMTxU8zj7sOFuD0bICK9
            dgQJkTfZBGggrTd1VZoacQ/vGQ7LOUQhgFmDyK8ey4Jp+5nyRfq4Fomg3wVXS1Z7
            xQvCEeP82v7z5f+356FqY6KLhKCQAes6IfCW14DAR5Jscm9z+PctfPWdRHMjqDOs
            uCfTsPMGQ9jhqD5T9Joc6Ov/VB2St3LCPDEculIvKZWtY3gvfPPcTZ2qmsLyJwIy
            ZDyrAzX87ZAd4uQoVlJ/ePRMpop/mSxwOmEMSw2qX3wp5Ie0X4q2rxbqPf/TU1If
            4Nm0zrOwr8ky0w3EtWkkHsFTRSmGN7+oaFCCQX3NxCXn/ZO7SL31WsFPVAIYmPAl
            LcfPzEstOeeIQk1eoD7nIvSDvv2sn2E4nKzIcH6SjDsPSVqcEvxY4kIGHub7q2LS
            XAHLQmB/TZWHD88gg6nNzjzfmjdLjbeOSsoCCbLhtdDwmoPm7OLsBPqzhTsxz/CB
            2hHADFJZACvU0GDhDiFxWTo+1M7He3SonpD0jRtVQtSVNrkz4toIsTA1Vyng
            =8hal
            -----END PGP MESSAGE-----
          fp: E715EC6CBDB31EC52BA974501CAE0ADA5A3D8EF4
        - created_at: "2021-09-11T01:51:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1qCpfMmo9y9AQ//diuKv5LvK9FNFiFYs6brs+UnQRnXGEEH+dJCWtQSPVIv
            c8hSiYzbNnbfK7BfKe4Jwzgo9no1BDO9yUXb+1hGizePR+3UCar2TlRzudRuI6YG
            VNRD+fDyk11Bi3p8wUqlXTHZaokAa5CHB0PoeTcH+n4Ix1eDyGQdCw0ru71gEjLr
            aVkwl+U2VzPco+a457cEwehRgw97RyneAF9Bj+angXWf2KzLAbzXbEduWJOEWwir
            dq5OBm56x+QqQkXcUxkX7rjgf6PvhZ5fW1Ow9EEC+BckPvA4ylY/6r6tcm+UoO1/
            8z9tCQ1wBunozFiZmg2pwyCLV+TCRM5nHU0hGEMNXSHnD9xa6V2XkVYjN+cbCXkJ
            gS6HG1npUjY4RlduXDqn50DfQ42LifNP4FMs8OxtjrsplCim+ou0YE7QiLGD2a10
            VQL0SD94gL+ajQNE1PnAcBaICDfUcHrn2/nwagXoJSBNMRzBJY5CX/s7fkU9mt66
            ZlmmbtMVuBD9EBCCStUSFMMojRMl7iEeIDYXf8HhKWfrwiSphBgT5ub4a5M5g7mn
            mhGF2cD8HEqDDWmaR7CSF8gh1iBjftO1j+30qd+1n6yGSzST0718ztrDjmwDfiaw
            JnuKHvbj7Zl411q2EvUfq9/Hh5FXxZTZ8GVtGzpXs2XnEtKKVt4i1gIeiNj0S2bS
            XAH0ZV9Ee0uoTsE4DySf4KITGDtrnVPX5hUBIBuEpwMLChQytP42M17mqg8xeRGt
            izbj0Qw5WiBNIRzzYJl9rbQPQIhzzxkXNmNMDTh4OkUWgWb0AeGBju3wl3Q3
            =Ko3J
            -----END PGP MESSAGE-----
          fp: 8A83E3391AAA2348759BCB51DCFF80A9EA3F7A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
