---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: valheim-server
    helm.toolkit.fluxcd.io/namespace: valheim
  name: valheim-server
  namespace: valheim
spec:
  ports:
    - name: gameport
      port: 2456
      protocol: UDP
      targetPort: 2456
    - name: queryport
      port: 2457
      protocol: UDP
      targetPort: 2457
  selector:
    app: valheim-server
  type: ClusterIP
