apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - podmonitor.yaml
configMapGenerator:
  - name: pihole-grafana-dashboards
    files:
      - pi-hole-exporter_rev2.json
    options:
      labels:
        grafana_dashboard: pihole
