apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: ceph-cluster-chart
    files:
      - ceph-cluster.json
    options:
      labels:
        grafana_dashboard: ceph-cluster
  - name: flux-grafana-dashboards
    files:
      - control-plane.json
      - cluster.json
    options:
      labels:
        grafana_dashboard: flux-system
